### ISSUE TITLE
Calling the "data" service for a publication annotation type results in a server 500 error

### ISSUE THREAD

**Issue by ahenrycgi** [cedadev/djcharme#10]
Request:

GET http://charme-dev.cems.rl.ac.uk/data/5b0958f20a4f412f859fa47b4580737a HTTP/1.1
Host: charme-dev.cems.rl.ac.uk
Proxy-Connection: keep-alive
Accept: application/ld+json, _/_; q=0.01
Origin: http://uk-l8071mx1.groupinfra.com:8090
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36
Referer: http://uk-l8071mx1.groupinfra.com:8090/DAV/js/charme/plugin/plugin.html?targetId=http%3A%2F%2Flocalhost%3A8090%2FDAV%2FNASA%2FChlorophyl%2F2003%2FMY1DMM_CHLORA_2003-01.JPEG
Accept-Encoding: gzip,deflate,sdch
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6

**Comment by kusamau** [comment]
Cannot reproduce. Do you still have such error?

**Comment by ahenrycgi** [comment]
No, it doesn’t seem to be happening now ☺ If it reoccurs I will let you know. Close it for now.
