### ISSUE TITLE
'Published' timestamp for annotations is not yet implemented

### ISSUE THREAD

**Issue by ahenrycgi** [cedadev/djcharme#14]
Returns a fixed timestamp - "TO_BE_DONE_2011-01-21T11:05:29.511Z"

**Comment by kusamau** [comment]
fixed in my local machine

**Comment by ahenrycgi** [comment]
Good stuff, thanks Maurizio. Can we prioritize getting this onto the live site? I want to try and get a functioning demo site up and running that’s fit for the public to see ☺
