### ISSUE TITLE
'Updated' and 'Published' dates are always 'today'

### ISSUE THREAD

**Issue by ahenrycgi** [cedadev/djcharme#17]
It seems that the results in the atom feed from the /search/ web service have funny dates associated with each of the entries. The two dates that are returned for each annotation are the 'updated' and 'published' dates, which seem to be the same, and are almost invariably today. I say almost invariably, I have at least one entry that is yesterday, but in either case, the annotations in question were created weeks ago. Could we please have the date that the annotations were created returned along with each annotation?

Additionally, I feel that this information should be stored against the annotations themselves via triples. The open annotation standard has provision to do this via the AnnotatedAt attribute - http://www.w3.org/ns/oa#d4e284

**Comment by antony-wilson** [comment]
Fixed in iteration 4
Annotations now include AnnotatedAt attribute
