### ISSUE TITLE
Requesting facets returns unexpected results

### ISSUE THREAD

**Issue by Alex-Wood-CGI** [cedadev/djcharme#25]
Requesting the facets for a particular target returns unexpected results: motivations, domains of interest and organizations that do not match the annotations against that target, with some facets missing and other facets returned that shouldn't be, e.g.:

![node_issue_suggest](https://cloud.githubusercontent.com/assets/6716823/3642405/614fba0a-10c1-11e4-95b5-78a93c0a0944.PNG)

**Comment by antony-wilson** [comment]
Please can you check that you are now getting back what you expect

**Comment by Alex-Wood-CGI** [comment]
Alas not… same as before.

**Comment by antony-wilson** [comment]
Could you paste the url you are looking at as it was a bit tricky copying it from an image and I may have made  mistake. I am seeing different results from ports 8027 and 443

**Comment by Alex-Wood-CGI** [comment]
It happens for any target, but here’s an example:
https://charme-dev.cems.rl.ac.uk/suggest/atom?status=submitted&q=*&target=http%3A%2F%2Flocalhost%3A8090%2FDAV%2FNASA%2FChlorophyl%2F2003%2FMY1DMM_CHLORA_2003-09.JPEG

**Comment by antony-wilson** [comment]
looking at 
https://charme-dev.cems.rl.ac.uk:8027/suggest/atom?count=25&status=submitted&q=*&target=http%3A%2F%2Flocalhost%3A8090%2FDAV%2FNASA%2FChlorophyl%2F2003%2FMY1DMM_CHLORA_2003-09.JPEG
and comparing it to the triple store it looks ok to me

There are 7 annotations for this target:
| http://charme-dev.cems.rl.ac.uk/resource/513f629971944609a6eec12859c8966a  |
| http://charme-dev.cems.rl.ac.uk/resource/65e5a3f02fe348b7b0bcd80de3ee9d62  |
| http://charme-dev.cems.rl.ac.uk/resource/dc398ac7778d46e694b561dff5c2e52f  |
| https://charme-dev.cems.rl.ac.uk/resource/012cae0a25e34409ba97b787c67350a6 |
| https://charme-dev.cems.rl.ac.uk/resource/2a0629a7cdd14fe099a4f7e5716eb4a0 |
| https://charme-dev.cems.rl.ac.uk/resource/63cadec1a21947eb92612b2f4ce6122c |
| https://charme-dev.cems.rl.ac.uk/resource/b4f0de33505343b0b124a59d17da0818 |

Some of the annotations have multiple domains of interest:
| anno                                                                         | domainOfInterest                                                                   |
| http://charme-dev.cems.rl.ac.uk/resource/513f629971944609a6eec12859c8966a  | "Angstrom Exponent"                                                                |
| http://charme-dev.cems.rl.ac.uk/resource/65e5a3f02fe348b7b0bcd80de3ee9d62  | "EARTH SCIENCE > Agriculture > Soils > Micronutrients/Trace Elements"              |
| http://charme-dev.cems.rl.ac.uk/resource/65e5a3f02fe348b7b0bcd80de3ee9d62  | "Micronutrients/Trace Elements"                                                    |
| http://charme-dev.cems.rl.ac.uk/resource/dc398ac7778d46e694b561dff5c2e52f  | "Shoals"                                                                           |
| https://charme-dev.cems.rl.ac.uk/resource/012cae0a25e34409ba97b787c67350a6 | "Defoliants"                                                                       |
| https://charme-dev.cems.rl.ac.uk/resource/2a0629a7cdd14fe099a4f7e5716eb4a0 | "Cation Exchange Capacity"                                                         |
| https://charme-dev.cems.rl.ac.uk/resource/63cadec1a21947eb92612b2f4ce6122c | "Barometric Altitude"                                                              |
| https://charme-dev.cems.rl.ac.uk/resource/b4f0de33505343b0b124a59d17da0818 | "EARTH SCIENCE > Agriculture > Forest Science > Forest Harvesting and Engineering" |
| https://charme-dev.cems.rl.ac.uk/resource/b4f0de33505343b0b124a59d17da0818 | "Forest Harvesting and Engineering"                                                |

There are multiple motivations for a number of the annotations:
| anno                                                                         | motivation     |
| http://charme-dev.cems.rl.ac.uk/resource/513f629971944609a6eec12859c8966a  | oa:editing     |
| http://charme-dev.cems.rl.ac.uk/resource/513f629971944609a6eec12859c8966a  | oa:tagging     |
| http://charme-dev.cems.rl.ac.uk/resource/65e5a3f02fe348b7b0bcd80de3ee9d62  | oa:bookmarking |
| http://charme-dev.cems.rl.ac.uk/resource/65e5a3f02fe348b7b0bcd80de3ee9d62  | oa:tagging     |
| http://charme-dev.cems.rl.ac.uk/resource/dc398ac7778d46e694b561dff5c2e52f  | oa:editing     |
| http://charme-dev.cems.rl.ac.uk/resource/dc398ac7778d46e694b561dff5c2e52f  | oa:tagging     |
| https://charme-dev.cems.rl.ac.uk/resource/012cae0a25e34409ba97b787c67350a6 | oa:commenting  |
| https://charme-dev.cems.rl.ac.uk/resource/012cae0a25e34409ba97b787c67350a6 | oa:tagging     |
| https://charme-dev.cems.rl.ac.uk/resource/2a0629a7cdd14fe099a4f7e5716eb4a0 | oa:commenting  |
| https://charme-dev.cems.rl.ac.uk/resource/2a0629a7cdd14fe099a4f7e5716eb4a0 | oa:tagging     |
| https://charme-dev.cems.rl.ac.uk/resource/63cadec1a21947eb92612b2f4ce6122c | oa:questioning |
| https://charme-dev.cems.rl.ac.uk/resource/63cadec1a21947eb92612b2f4ce6122c | oa:tagging     |
| https://charme-dev.cems.rl.ac.uk/resource/b4f0de33505343b0b124a59d17da0818 | oa:identifying |
| https://charme-dev.cems.rl.ac.uk/resource/b4f0de33505343b0b124a59d17da0818 | oa:tagging     |

**Comment by Alex-Wood-CGI** [comment]
It’s a port issue (you mentioned seeing different results on different ports) – it works on 8027, but only on 8027.

**Comment by antony-wilson** [comment]
port 443 is iteration 4, it will get updated when everyone is happy with the lasest code
port 8027 is the latest code moving towards iteration 5

To avoid confusion we will soon be putting these on seperate machines and improving the release process

**Comment by antony-wilson** [comment]
fixed in ieration 5
