### ISSUE TITLE
Person object in annotation graphs

### ISSUE THREAD

**Issue by Alex-Wood-CGI** [cedadev/djcharme#27]
When viewing an individual annotation, the graph returned includes a Person object which contains "http://xmlns.com/foaf/0.1/accountName". However, when searching the annotations against a target, the graphs returned do not include accountName in their Person objects. Please include accountName every time.

![node_issue_accountname1](https://cloud.githubusercontent.com/assets/6716823/4118015/352259dc-329b-11e4-895b-bdd29a558971.PNG)

![node_issue_accountname2](https://cloud.githubusercontent.com/assets/6716823/4118021/406e62f4-329b-11e4-8389-fca85e25a808.PNG)

**Comment by antony-wilson** [comment]
Lets discuss this on Thursday. I think the bug is that the accountName is showing up in the individual record.

**Comment by Alex-Wood-CGI** [comment]
Actually we want accountName to appear, every time!

**Comment by antony-wilson** [comment]
accountName added for iteration 5
