### ISSUE TITLE
DELETE is not allowed by Access-Control-Allow-Methods

### ISSUE THREAD

**Issue by indranilm** [cedadev/djcharme#29]
DELETE request on an annotation receives the message 
"Method DELETE is not allowed by Access-Control-Allow-Methods. "

The delete request is of the form  
# 

resource/(w+)
Action: Moves the resource to the 'retired' graph
HTTP Method: DELETE

for e.g.
https://charme-dev.cems.rl.ac.uk/resource/a2d23569a7ee475ba47303348104a023

**Comment by antony-wilson** [comment]
fix is on https://charme-dev.cems.rl.ac.uk
