### ISSUE TITLE
URL stored as both citation act and link

### ISSUE THREAD

**Issue by Alex-Wood-CGI** [cedadev/djcharme#32]
A user includes a link in an annotation. If the user selects type 'Journal Article' or 'Conference Paper', then it is treated as a citation act, otherwise it's just a link. Also, the same URL may be given different types, e.g. Alice's annotation includes a link to www.example.com and classifies it as Journal Article. Bob then includes the same link in his annotation but calls it a Conference Report. If you now view either Alice's or Bob's annotation, both classification tags - Journal Article and Conference Paper - will be displayed. So far so good.

But then Carol includes the same link and calls it a Technical Report, Dan's annotation calls it a Validation Report, and Erin calls it a Product User Manual. Now, viewing Alice's or Bob's annotation will still display only two tags: Journal Article and Conference Paper. Viewing the annotations by Carol, Dan or Erin will display three tags: Technical Report, Validation Report and Product User Manual. The node doesn't realise that the same URL has been given five different tags, and nor will this be clear to the user, who may be confused if for example they view Alice's annotation and then Carol's.

Can the node be made to recognise when a URL has been included as both a citation act and as an ordinary link?

**Comment by antony-wilson** [comment]
Why do you restrict citations to 'Journal Article' and 'Conference Paper'? All of the FaBiO classes should be able to be citing entities.

**Comment by Alex-Wood-CGI** [comment]
I believe it was agreed with STFC that Journal Article and Conference Paper should _always_ be citation acts, hence they are hardwired to be so. Yes, maybe the other types could also be citation acts; I remember the idea was discussed of perhaps having a checkbox whereby the user can explicitly choose whether the resource they're attaching is a citation act or not, but this has not been implemented (at least not yet). And anyway, regardless of whether it's implemented or not, the problem remains: if one user has attached a resource as a citation act, and another has attached it as just a link, then the node should recognise this. In the example I described, viewing any of the annotations should display all five tags. Can this be done?

**Comment by antony-wilson** [comment]
Yes the tick box was discussed a while ago and at the final review we agreed that it would be good to have.

When I test this with doi://example.edu/paper/01 as a cito:hasCitingEntity and then a oa:hasBody I see all the types for doi://example.edu/paper/01
Please can you paste in an example of the json generated by Alice and the json generated by Carol.
